language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

jobs:
  include:
    - stage: lint
      script: ./gradlew lint
    - stage: build
      script: ./gradlew assembleDebug
    - stage: test
      script: ./gradlew test

notifications:
  slack: mini-capstone-konoha:0QohlfBAaXz34wuCg2SJMQZo
