language: android
android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra

script: 
- echo "Hello"
- ./gradlew -v
- ./gradlew build
- ./gradlew test

notifications:
  slack: mini-capstone-konoha:0QohlfBAaXz34wuCg2SJMQZo
